package org.scalatest.tools

import java.net.URLEncoder
import java.nio.charset.StandardCharsets

import org.scalatest._
import org.scalatest.events._
import scalaj.http.{HttpResponse, Http}
import spray.json._
import DefaultJsonProtocol._
import org.slf4j._

class JUnitReporter extends Reporter with App {
  case class Project(
      id: String,
      name: String,
      description: String,
      projectType: String,
      creationDate: Long
  )
  case class ExecutionRequest(
      projectId: String,
      description: String,
      host: String,
      parallel: Boolean,
      environment: String,
      branch: String,
      buildRef: String,
      tags: List[String]
  )
  case class ExecutionResponse(id: String)
  case class ScenarioRequest(
      projectId: String,
      featureName: String,
      featureDescription: String,
      name: String,
      tags: List[String],
      steps: IndexedSeq[StepRequest]
  )
  case class StepRequest(index: Int, text: String, dataTableRows: List[String])
  def log: Logger = LoggerFactory.getLogger("TestraReporter")

  var apiUrl = ""
  var project = ""
  var executionId = ""
  var projectId = ""
  override def apply(event: Event): Unit = {
    event match {
      case e: RunStarting =>
        e.configMap.get("testraApi") match {
          case Some(i) => apiUrl = i.asInstanceOf[String]
          case None    => println("No url found for testra")
        }
        initialiseTestra

      case e: TestSucceeded =>
        createScenario(e)
      // e.recordedEvents.foreach {
      //   case r: InfoProvided =>
      //   case _               =>
      // }
      case _ =>
    }
  }

  def initialiseTestra: Unit = {
    project = "Companion Service"
    log.info(s"Testra Url $apiUrl")
    log.info(s"Project: $project")
    getProjectId
    createExecutionId
  }

  def getProjectId: Unit = {
    implicit val projectFormat: JsonFormat[Project] = jsonFormat5(Project)
    val response: HttpResponse[String] = Http(
      apiUrl + "/projects/" + URLEncoder
        .encode(project, StandardCharsets.UTF_8.toString)
        .replace("+", "%20")
    ).asString
    projectId = response.body.parseJson.convertTo[Project].id
    log.info(s"Project ID $projectId found")
  }

  def createExecutionId: Unit = {
    implicit val execution: JsonFormat[ExecutionRequest] = jsonFormat8(
      ExecutionRequest
    )
    implicit val executionResponse: JsonFormat[ExecutionResponse] = jsonFormat1(
      ExecutionResponse
    )

    val executionRequest = ExecutionRequest(
      projectId,
      "Generated by Scalatest Plugin",
      "host",
      false,
      "cosmic-dev",
      "Develop",
      "buildRef",
      List("paul.johnson2@sky.uk")
    )
    executionId = Http(
      apiUrl + "/projects/" + projectId + "/executions"
    ).postData(executionRequest.toJson.compactPrint)
      .header("content-type", "application/json")
      .asString
      .body
      .parseJson
      .convertTo[ExecutionResponse]
      .id
    log.info("Execution Id set to " + executionId)

  }

  def createScenario(event: TestSucceeded) {
    implicit val stepreq: JsonFormat[StepRequest] = jsonFormat3(
      StepRequest
    )

    implicit val scenarioreq: JsonFormat[ScenarioRequest] = jsonFormat6(
      ScenarioRequest
    )
    var counter = -1;
    val scenario = ScenarioRequest(
      projectId,
      event.suiteName,
      "Feature name generated from class name",
      event.testName,
      List[String](),
      event.recordedEvents.collect {
        case a: InfoProvided =>
          counter+=1
          StepRequest(counter, a.message, List[String]())
      }
    )
    println(scenario.toJson.prettyPrint)
  }

}
